// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRUogAayFphrtSHjZfzQG_GALiVFKCMvk',
    appId: '1:156659680045:android:0d383fe19da19911c909a4',
    messagingSenderId: '156659680045',
    projectId: 'mynotes-flutter-project-cbd54',
    storageBucket: 'mynotes-flutter-project-cbd54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC91ANS1umvzgQfJ5e4kJe5-3vcUUQSb0E',
    appId: '1:156659680045:ios:b2ddee7d4d33dc48c909a4',
    messagingSenderId: '156659680045',
    projectId: 'mynotes-flutter-project-cbd54',
    storageBucket: 'mynotes-flutter-project-cbd54.appspot.com',
    iosClientId: '156659680045-mhj1hvo7hb6908fs5g6vp526i8bjgvaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
